#!/usr/bin/env python3
"""Generate the static ArkTS emoji catalog from Unicode emoji-test.txt."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


GROUPS = (
    ("Smileys & Emotion", "smileys", "😀"),
    ("People & Body", "people", "👋"),
    ("Animals & Nature", "animals", "🐻"),
    ("Food & Drink", "food", "🍔"),
    ("Travel & Places", "travel", "🚗"),
    ("Activities", "activity", "⚽"),
    ("Objects", "objects", "💡"),
    ("Symbols", "symbols", "❤️"),
    ("Flags", "flags", "🏳️"),
)


def parse_catalog(source: Path) -> tuple[str, dict[str, list[str]]]:
    text = source.read_text(encoding="utf-8")
    version = ""
    active_group = ""
    groups: dict[str, list[str]] = {name: [] for name, _, _ in GROUPS}
    for line in text.splitlines():
        if line.startswith("# Version:"):
            version = line.split(":", 1)[1].strip()
        elif line.startswith("# group: "):
            active_group = line[9:]
        elif "; fully-qualified" in line and active_group in groups:
            code_points = [int(value, 16) for value in line.split(";", 1)[0].strip().split()]
            # Telegram-style palettes show one neutral/base cell and expose tone
            # variants contextually; do not multiply the grid with modifier rows.
            if any(0x1F3FB <= value <= 0x1F3FF for value in code_points):
                continue
            groups[active_group].append("".join(chr(value) for value in code_points))
    if not version:
        raise ValueError("Unicode emoji version header is missing")
    if any(not groups[name] for name, _, _ in GROUPS):
        raise ValueError("One or more Unicode keyboard groups are empty")
    return version, groups


def render_array(values: list[str]) -> list[str]:
    lines: list[str] = []
    for offset in range(0, len(values), 12):
        chunk = ", ".join(json.dumps(value, ensure_ascii=False) for value in values[offset:offset + 12])
        lines.append(f"    {chunk}")
    return lines


def generate(source: Path, output: Path) -> None:
    version, groups = parse_catalog(source)
    source_hash = hashlib.sha256(source.read_bytes()).hexdigest().upper()
    total = sum(len(values) for values in groups.values())
    if total < 1500:
        raise ValueError(f"Catalog is unexpectedly small: {total}")

    lines = [
        "// Generated by scripts/generate-unicode-emoji-catalog.py. Do not hand-edit.",
        f"// Source: Unicode emoji-test.txt {version} (CLDR keyboard order, fully-qualified base sequences).",
        "// https://www.unicode.org/Public/emoji/latest/emoji-test.txt",
        f"// Source SHA-256: {source_hash}",
        "",
        "export class UnicodeEmojiCategory {",
        "  readonly id: string;",
        "  readonly icon: string;",
        "  readonly emojis: string[];",
        "",
        "  constructor(id: string, icon: string, emojis: string[]) {",
        "    this.id = id;",
        "    this.icon = icon;",
        "    this.emojis = emojis;",
        "  }",
        "}",
        "",
        f"export const UNICODE_EMOJI_VERSION: string = {json.dumps(version)};",
        f"export const UNICODE_EMOJI_COUNT: number = {total};",
        "",
        "export const UNICODE_EMOJI_CATEGORIES: UnicodeEmojiCategory[] = [",
    ]
    for group_name, group_id, icon in GROUPS:
        lines.append(
            f"  new UnicodeEmojiCategory({json.dumps(group_id)}, {json.dumps(icon, ensure_ascii=False)}, ["
        )
        values = groups[group_name]
        array_lines = render_array(values)
        for index, array_line in enumerate(array_lines):
            suffix = "," if index < len(array_lines) - 1 else ""
            lines.append(array_line + suffix)
        lines.append("  ]),")
    lines.extend(("];", ""))

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"Generated {output} with {total} base emoji across {len(GROUPS)} groups (Unicode {version})")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("entry/src/main/ets/ui/tg_ui/data/TgUnicodeEmojiCatalog.ets"),
    )
    args = parser.parse_args()
    generate(args.input, args.output)


if __name__ == "__main__":
    main()
